apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-container-pod
  name: multi-container-pod
spec:
  containers:
  - command:
    - sleep
    - "3600"
    env:
    - name: name
      value: shubham
    - name: age
      value: "27"
    image: busybox
    name: multi-container-pod
  initContainers:
    - name: init-container-pod
      command: ['sh', '-c', "until nslookup myservice.default.svc.cluster.local; do echo waiting for myservice; sleep 2; done"]
      image: busybox
    - name: init-container-pod2
      command: ['sh', '-c', "until nslookup myservice2.default.svc.cluster.local; do echo waiting for myservice; sleep 2; done"]
      image: busybox
