apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-container-pod
  name: multi-container-pod
spec:
  containers:
  - env:
    - name: name
      value: shubham
    - name: age
      value: "27"
    image: sidecar
    name: multi-container-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
