apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-untainted
  name: nginx-untainted
spec:
  tolerations:
  - key: "gpu"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  containers:
  - image: nginx
    name: nginx-untainted
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
