apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec2
spec:
  containers:
  - name: liveness2
    image: registry.k8s.io/e2e-test-images/agnhost:2.40
    ports:
    - containerPort: 8080
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
      initialDelaySeconds: 5
      periodSeconds: 10
