apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: redis-affinity
  name: redis-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: Exists
  containers:
  - image: redis
    name: redis-affinity
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
